### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by bogdanbiv** [bogdanbiv/relayBootServer#2]
## Project Plan (nov 2015)
1. Start with Relay Starter Kit
   - npm install
   - smoke tests
2. [Verify Webpack/React Transform features](../../issues/1)
   - [x] Simple React Component is rendered
   - [x] JSX transform
   - [x] Hot Module Reload
   - [x] Red Error flasher
   - [x] ES2015 support on the client
3. Verify GraphQL features
   - [ ] [Compose schema sources](issues/4)
   - [ ] Graffiti based schema
   - [ ] schema with REST backend/s
   - [ ] seed database / backend/s
4. Webserver features 
   - change Express to Koa, port middleware to use koa generators
   - add Lusca for security
   - port middleware to use generators
   - check http2 support in NodeJS (also check Webpack for compat)
   - TLS encryption
   - Detect connection performance (server ?)
5. Logging & monitoring
   - bunyan
   - weston
6. Authentication & Authorization:
   - One approach to authentication/authorization with GraphQL-based server - https://github.com/mostr/graphql-auth
   - Limit introspection capability programatically - https://github.com/graphql/graphql-js/issues/113
7. Test suite
   - Unit test components
   - Component integration
   - Mocha, Chai, Sinon
   - WebDriver ?
   - Karma (other runners ?)
8. Task runner
   - Gulp / Slush
   - Fly / Flightplan
   - Deployment task
   - Generate static site via React (server side) - during idle time
   - Re/Generate schema (data/schema.json) and restart server
   - Seed database
9. Cluster support
   - Geo-optimisation ?
   - latency ?
10. React tools
    - GraphiQL
    - Playground
    - Block editors (Structor, Kattappa, Colonel Kurtz)
